name: Build opencv with Wechat QRCode

on:
  push:
    tags: ['build-[0-9]+.[0-9]+.[0-9]+']

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build WechatQRCode Android SDK with opencv
        run : |
          chmod +x ${GITHUB_WORKSPACE}/scripts/build_android_sdk.sh
          ./${GITHUB_WORKSPACE}/scripts/build_android_sdk.sh
